# Generated by Django 4.2.5 on 2023-09-27 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dadosIOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.IntegerField()),
                ('hw_vers', models.CharField(max_length=10)),
                ('sw_vers', models.CharField(max_length=10)),
                ('set_point', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('humidade', models.FloatField()),
                ('data_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='estufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeIOT', models.CharField(max_length=10)),
                ('senhaIOT', models.CharField(max_length=20)),
                ('capacidade', models.IntegerField()),
                ('status', models.CharField(choices=[('produzindo', 'produzindo'), ('erro', 'erro'), ('parada', 'parada')], default='produzindo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_inicial', models.FloatField()),
                ('peso_final', models.FloatField()),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField(null=True)),
                ('temperatura', models.FloatField()),
                ('situacao', models.CharField(choices=[('preparando', 'preparando'), ('iniciado', 'iniciado'), ('cancelado', 'cancelado'), ('finalizado', 'finalizado'), ('reservado', 'reservado'), ('vendido', 'vendido')], default='preparando', max_length=20)),
                ('valor', models.FloatField()),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annsite.estufa')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('prepago', models.FloatField(default=0)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annsite.lote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annsite.lote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
