# Generated by Django 4.0.4 on 2023-10-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annsite', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosiot',
            name='serialNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
