# Generated by Django 4.0.4 on 2023-10-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annsite', '0003_dadosiot_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='peso_final',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
